#!/bin/bash
echo "=== Unity License для GitHub Actions ==="
echo ""
echo "GameCI больше не использует .alf файлы."
echo "Нужен .ulf файл с машины где установлен Unity."
echo ""
echo "=== Как получить .ulf ==="
echo ""
echo "1. Установи Unity Hub на любой машине (Mac/Windows/Linux)"
echo "2. Залогинься в свой Unity аккаунт"
echo "3. Preferences → Licenses → Get a free personal license"
echo "4. Найди файл Unity_lic.ulf:"
echo "   - Windows: C:\ProgramData\Unity\Unity_lic.ulf"
echo "   - Mac:     /Library/Application Support/Unity/Unity_lic.ulf"
echo "   - Linux:   ~/.local/share/unity3d/Unity/Unity_lic.ulf"
echo ""
echo "=== Как добавить в GitHub ==="
echo ""
echo "5. Открой https://github.com/AkkAshy/UrbanScanVR/settings/secrets/actions"
echo "6. Добавь 3 секрета:"
echo "   - UNITY_LICENSE = содержимое Unity_lic.ulf файла"
echo "   - UNITY_EMAIL   = email Unity аккаунта"
echo "   - UNITY_PASSWORD = пароль Unity аккаунта"
echo ""
echo "7. Запусти Build: Actions → Build UrbanScanVR → Run workflow"
