#!/bin/bash
echo "=== Unity License Activation ==="
echo ""
echo "На Mac с Apple Silicon Docker не поддерживает Unity образы."
echo "Используй GitHub Actions для получения лицензии:"
echo ""
echo "1. Запушь проект на GitHub"
echo "2. Перейди в Actions → 'Get Unity License' → Run workflow"
echo "3. Скачай artifact Unity_v2022.3.45f1.alf"
echo "4. Открой https://license.unity3d.com/manual"
echo "5. Загрузи .alf файл → скачай .ulf файл"
echo "6. В GitHub → Settings → Secrets → Actions добавь:"
echo "   - UNITY_LICENSE = содержимое .ulf файла"
echo "   - UNITY_EMAIL = email Unity аккаунта"
echo "   - UNITY_PASSWORD = пароль Unity аккаунта"
echo ""
echo "После этого запусти 'Build UrbanScanVR' workflow!"
